#flask_blog/config.py

SQLARCHEMY_DATABASE_URI='sqlite:///flask_blog.db'
SQLARCHEMY_TRACK_MODIFICATION=True
SQLARCHEMY_TRACK_MODIFICATIONS=True
DEBUG=True
SECRET_KEY='secret key'
SQLALCHEMY_DATABASE_URI = 'sqlite:///flask_blog.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
DEBUG = True
SECRET_KEY = 'secret key'
>>>>>>> 0bfe650054edfbad2dc0f6864326c5b537dde2d3
USERNAME='hoge'
PASSWORD='hoge'